// src/components/react/Header.tsx
import React, { useEffect, useRef, useState } from "react";
import { trackEvent } from "@/utils/window";
import { PublishButton } from "./PublishButton";
import { setupCloseGuard } from "@/utils/closeGuard";
import { makeDebouncedDraftSaver, loadDraft, clearDraft, primeCloudId, getCachedCloudId, getCachedSavedVersionUpdatedAt, saveDraftSync, isDraftNewerThanSaved } from "@/utils/draftStore";
import EventBus from "@/EventBus";
import yaml from "js-yaml";
import { openUrl } from "@/model/globals/forgeGlobal";
import { getOpenApiTitleField } from '@/model/OpenApi/OpenApiEditorState';
import OpenApiTitleInput from '@/components/react/OpenApiTitleInput';
import store from '@/model/store2';

// Docs link for the OpenAPI editor's Help button — mirrors the URL the Vue
// header uses (components/Header/Header.vue). Opened via openUrl() because a
// plain <a target="_blank"> is sandboxed/blocked inside the Forge Custom UI
// iframe; openUrl routes through @forge/bridge's router.open under Forge.
const HELP_URL =
  "https://zenuml.com/docs?utm_source=confluence-plugin&utm_medium=help-button&utm_campaign=confluence-plugin";

interface Props {
  saveAndExit: VoidFunction;
  exit: VoidFunction;
}
const Component = ({ saveAndExit, exit }: Props) => {
  const [title, setTitle] = useState("");
  const [spec, setSpec] = useState(() => window.specContent ?? window.diagram?.code ?? '');
  const [parseError, setParseError] = useState<Error | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const originalSpec = useRef<string | null>(null);
  const onRestoreRef = useRef<((p: any) => void) | null>(null);
  const savingTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Show the spinner immediately on Publish — the async save chain
  // (saveToPlatform → view.submit) takes seconds with no other feedback, and
  // the button would otherwise stay clickable (double-fire). Cleared on the
  // `saved`/`save-error` events below.
  const handleSaveAndExit = () => {
    if (isSaving) return;
    setIsSaving(true);
    if (savingTimeoutRef.current) clearTimeout(savingTimeoutRef.current);
    // Safety net so an unexpected hang can't strand the spinner.
    savingTimeoutRef.current = setTimeout(() => setIsSaving(false), 20000);
    saveAndExit();
  };

  // Persist drafts (per keystroke + on close) so accidental Atlassian-X close
  // can be recovered on next open. See src/utils/closeGuard.ts for why we
  // dropped beforeunload. Capture the baseline lazily because Swagger UI
  // injects window.diagram.code asynchronously.
  useEffect(() => {
    let cancelled = false;
    const captureBaseline = (spec: string) => {
      if (originalSpec.current === null && spec) {
        originalSpec.current = spec;
      }
    };
    captureBaseline(window.specContent ?? window.diagram?.code ?? '');

    if (!window.specListeners) window.specListeners = [];
    window.specListeners.push(captureBaseline);

    const diagramId = (window as any).diagram?.id;
    const scope = diagramId ? `edit:${diagramId}` : 'new:openapi';
    const saver = makeDebouncedDraftSaver(scope, 500);
    let saveOnChange: ((spec: string) => void) | null = null;

    let closeGuardOff: (() => void) | null = null;
    let onSaved: ((id: string) => void) | null = null;
    let onSaveError: (() => void) | null = null;

    const resetSaving = () => {
      setIsSaving(false);
      if (savingTimeoutRef.current) {
        clearTimeout(savingTimeoutRef.current);
        savingTimeoutRef.current = null;
      }
    };

    (async () => {
      await primeCloudId();
      if (cancelled) return;

      // Restore prompt if a newer draft is sitting in localStorage.
      const draft = await loadDraft(scope);
      if (draft) {
        const baseline = originalSpec.current ?? '';
        const savedVersionUpdatedAt = getCachedSavedVersionUpdatedAt() ?? (window as any).diagram?.updatedAt;
        if (isDraftNewerThanSaved(draft, savedVersionUpdatedAt) && draft.code !== baseline) {
          EventBus.$emit('draft-available', { scope, draft });
        } else {
          await clearDraft(scope);
        }
      }

      // Per-keystroke draft via Swagger's spec listener pipeline.
      saveOnChange = (spec: string) => {
        if (originalSpec.current === null || spec === originalSpec.current) return;
        saver.save({ code: spec, title: (window as any).diagram?.title || '' });
      };
      window.specListeners!.push(saveOnChange);

      // view.onClose: synchronously flush the latest spec to localStorage.
      closeGuardOff = setupCloseGuard(() => {
        const current = window.specContent ?? window.diagram?.code ?? '';
        if (originalSpec.current === null || current === originalSpec.current) return;
        const cloudId = getCachedCloudId();
        if (cloudId) {
          saveDraftSync(scope, cloudId, {
            code: current,
            title: (window as any).diagram?.title || '',
          });
        }
      });

      // Clear draft + release the Publish button after a successful publish.
      onSaved = () => {
        resetSaving();
        saver.cancel();
        clearDraft(scope);
      };
      EventBus.$on('saved', onSaved);

      // Release the Publish button when a save fails — the editor stays open
      // for retry (see forge-swagger-editor.ts), so the spinner must clear.
      onSaveError = () => resetSaving();
      EventBus.$on('save-error', onSaveError);

      // Restore handler: push the draft spec into Swagger UI.
      const onRestore = (payload: any) => {
        if (payload?.scope !== scope || !payload?.draft) return;
        try {
          (window as any).editor?.specActions?.updateSpec(payload.draft.code);
          if (payload.draft.title && (window as any).diagram) {
            (window as any).diagram.title = payload.draft.title;
          }
          originalSpec.current = ''; // force restored content to count as dirty
          clearDraft(scope);
        } catch (e) {
          console.error('[draft-restore] openapi restore failed', e);
        }
      };
      (onRestoreRef as any).current = onRestore;
      EventBus.$on('draft-restore', onRestore);
    })();

    return () => {
      cancelled = true;
      if (window.specListeners) {
        window.specListeners = window.specListeners.filter(l => l !== captureBaseline && l !== saveOnChange);
      }
      saver.flush();
      closeGuardOff?.();
      if (savingTimeoutRef.current) clearTimeout(savingTimeoutRef.current);
      if (onSaved) EventBus.$off('saved', onSaved);
      if (onSaveError) EventBus.$off('save-error', onSaveError);
      if (onRestoreRef.current) EventBus.$off('draft-restore', onRestoreRef.current);
    };
  }, []);

  const helpClick = () => {
    trackEvent("help", "click", "open-api");
    void openUrl(HELP_URL);
  };

  const setTitleWithSideEffect = (value: string) => {
    setTitle(value);
    store.dispatch('updateTitle', value);
    if (window.diagram) {
      window.diagram.title = value;
    }
  };

  const changeTitle = (value: string) => {
    setTitleWithSideEffect(value);
    if (window.diagram) {
      try {
        yaml.loadAll(window.specContent || spec || '', function (data) {
          if (!data) return;
          const doc: Record<string, any> = data as any;
          if (doc && doc.info) {
            doc.info.title = value;
            window.editor.specActions.updateSpec(yaml.dump(doc));
          }
        });
        setParseError(null);
      } catch (error) {
        console.error("Error parsing YAML:", error);
        setParseError(error instanceof Error ? error : new Error(String(error)));
        // Still update the title in the UI even if YAML parsing fails
      }
    }
  };
  
  useEffect(() => {
    if (window.diagram) {
      try {
        setSpec(window.diagram.code || '');
        yaml.loadAll(window.diagram.code || '', function (data) {
          if (!data) return;
          const doc: Record<string, any> = data as any;
          const nextTitle = getOpenApiTitleField(doc);
          if (nextTitle !== undefined) setTitleWithSideEffect(nextTitle);
        });
        setParseError(null);
      } catch (error) {
        console.error("Error parsing YAML in useEffect:", error);
        setParseError(error instanceof Error ? error : new Error(String(error)));
      }
    }
    
    const handleEditorChange = (spec: string) => {
      setSpec(spec);
      try {
        yaml.loadAll(spec, function (data) {
          if (!data) return;
          const doc: Record<string, any> = data as any;
          const nextTitle = getOpenApiTitleField(doc);
          if (nextTitle !== undefined) {
            setTitleWithSideEffect(nextTitle);
          }
        });
        setParseError(null);
      } catch (error) {
        console.error("Error parsing YAML in editor change:", error);
        setParseError(error instanceof Error ? error : new Error(String(error)));
        // Keep the existing title if parsing fails
      }
    };
    
    if (!window.specListeners) window.specListeners = [];
    window.specListeners.push(handleEditorChange);
    return () => {
      if (!window.specListeners) return
      window.specListeners = window.specListeners.filter(
        (listener: any) => listener !== handleEditorChange
      );
    };
  }, []);

  return (
    <header className="toolbar header border-b border-gray-800 p-2 flex items-center justify-between w-full">
      <OpenApiTitleInput
        title={title}
        spec={spec}
        parseError={parseError}
        onTitleChange={changeTitle}
      />
      <div className="flex items-center">
        <button
          type="button"
          className="help mx-1 ml-2 flex items-center bg-gray-100 px-2 py-1 text-gray-600 text-sm font-semibold rounded hover:bg-gray-200 cursor-pointer"
          onClick={helpClick}
        >
          <span>
            <svg
              className="w-4 h-4"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
              ></path>
            </svg>
          </span>
          <span>Help</span>
        </button>
        <div className="inline-block ml-2">
          <PublishButton saveAndExit={handleSaveAndExit} disabled={!title} loading={isSaving} />
        </div>
      </div>
    </header>
  );
};

export default Component;

// src/components/Header/Header.vue
<template>
  <header class="toolbar header border-b border-gray-200 px-6 py-3 flex items-center gap-3 relative z-10 h-14">
    <div class="flex items-center gap-3 flex-1 min-w-0">
      <TabSwitcher
        v-model="diagramType"
        :options="diagramOptions"
      />
      <DiagramTitleInput />
    </div>
    <div class="flex items-center gap-3 shrink-0">
      <button class="flex items-center gap-1.5 px-2.5 py-1.5 text-gray-500 text-sm font-medium rounded-md hover:text-gray-700 hover:bg-gray-100 transition-colors duration-200"
        @click="templateClick">
        <LightBulbIcon class="w-4 h-4" />
        <span>Examples</span>
      </button>
      <button class="flex items-center gap-1.5 px-2.5 py-1.5 text-gray-500 text-sm font-medium rounded-md hover:text-gray-700 hover:bg-gray-100 transition-colors duration-200"
        @click="helpClick">
        <QuestionMarkCircleIcon class="w-4 h-4" />
        <span>Help</span>
      </button>
      <div class="h-6 w-px bg-gray-300"></div>
      <div class="relative group/save">
        <publish-button
          :saveAndExit="saveAndExit"
          :disabled="isPublishDisabled"
          :loading="isSaving" />
        <div class="absolute top-full right-0 pt-2 pointer-events-none opacity-0 transition-opacity duration-150"
          :class="isPublishDisabled ? 'group-hover/save:opacity-100' : ''">
          <div class="shadow-lg px-3 py-2 bg-gray-900 text-white text-xs rounded-md max-w-xs w-max">
            {{ publishDisabledHint }}
          </div>
        </div>
      </div>
    </div>
  </header>
</template>

<script>
import { mapState, mapMutations } from "vuex";
import PublishButton from "@/components/PublishButton.vue";
import TabSwitcher from "@/components/TabSwitcher/TabSwitcher.vue";
import { setupCloseGuard } from "@/utils/closeGuard";
import { makeDebouncedDraftSaver, loadDraft, clearDraft, primeCloudId, getCachedCloudId, saveDraftSync } from "@/utils/draftStore";
import { DiagramType } from "@/model/Diagram/Diagram";
import { getEditorDiagramOptions, getDiagramConfig, getCodeFromDiagram, getStoreUpdateAction } from "@/model/Diagram/DiagramTypeConfig";
import EventBus from "@/EventBus";
import { trackEvent } from "@/utils/window";
import { getEditJourneyId, getOrCreateSession } from "@/utils/journeyTracking";
import { openUrl } from "@/model/globals/forgeGlobal";
import LightBulbIcon from '@heroicons/vue/24/outline/LightBulbIcon';
import QuestionMarkCircleIcon from '@heroicons/vue/24/outline/QuestionMarkCircleIcon';
import DiagramTitleInput from "@/components/Header/DiagramTitleInput.vue";
import { PUBLISH_BLOCK_MESSAGES } from "@/model/editDupGate";

export default {
  name: "Header",
  components: {
    PublishButton,
    TabSwitcher,
    DiagramTitleInput,
    LightBulbIcon: { render: LightBulbIcon },
    QuestionMarkCircleIcon: { render: QuestionMarkCircleIcon },
  },
  data() {
    return {
      helpUrl: "https://zenuml.com/docs?utm_source=confluence-plugin&utm_medium=help-button&utm_campaign=confluence-plugin",
      originalCode: "",
      diagramOptions: getEditorDiagramOptions(),
      // Drives the Publish button's spinner + disabled state while the async
      // save/publish chain (saveToPlatform → attachment upload → view.submit)
      // is in flight. Without this the button sits inert for 2–8s with no
      // feedback and stays clickable, so an impatient user can double-fire.
      isSaving: false,
    };
  },
  computed: {
    DiagramType() {
      return DiagramType;
    },
    diagramType: {
      get() {
        return this.$store.state.diagram.diagramType;
      },
      set(value) {
        this.updateDiagramType(value);
        // Save user's tab preference to localStorage
        localStorage.setItem('zenuml-preferred-diagram-type', value);
      }
    },
    ...mapState({
      templateUrl: (state) =>
        getDiagramConfig(state.diagram.diagramType)?.templateUrl || '',
    }),
    currentCode() {
      return getCodeFromDiagram(this.$store.state.diagram, this.diagramType);
    },
    saveAndExit: function () {
      return () => {
        if (!this.$store.state.diagram.title) {
          EventBus.$emit("flash-title-error");
          return;
        }
        if (this.isSaving) return; // guard against double-fire
        this.startSaving();
        EventBus.$emit("save");
      };
    },
    exit: function () {
      return () => {
        const codeChanged = this.currentCode !== this.originalCode;

        // Determine if creating new or editing existing
        const isNew = !this.$store.state.diagram.id;
        const eventAction = isNew ? 'before_create_macro_exit' : 'before_edit_macro_exit';

        // Track exit button click with journey context
        trackEvent("", eventAction, this.diagramType, {
          had_changes: codeChanged,
          title_provided: !!this.$store.state.diagram.title,
          source: "header_exit_button",
          journey_id: getEditJourneyId(),
          session_id: getOrCreateSession(),
          initial_code_length: this.originalCode?.length || 0,
          current_code_length: this.currentCode?.length || 0,
        });

        EventBus.$emit("exit", codeChanged);
      };
    },
    isPublishDisabled: function () {
      return !this.$store.state.diagram.title || !!this.$store.state.publishBlock;
    },
    publishDisabledHint: function () {
      // publishBlock (model/editDupGate.ts): this editor surface cannot link
      // a forked CC back into the macro — publishing here would silently
      // strand the edit. Wins over the title hint.
      const block = this.$store.state.publishBlock;
      if (block) return PUBLISH_BLOCK_MESSAGES[block] || 'Publishing is unavailable for this diagram here.';
      return 'Add a diagram title to publish';
    },
  },
  methods: {
    ...mapMutations(["updateDiagramType"]),
    startSaving() {
      this.isSaving = true;
      // Safety net: if neither `saved` nor `save-error` comes back (e.g. an
      // unexpected hang), release the button so the user isn't stranded on a
      // spinner. Set comfortably above the worst-case happy path: saveToPlatform
      // network time + the 8s save-time attachment cap + the 500ms writeback
      // delay in forgeIndex.ts.
      clearTimeout(this._savingTimeout);
      this._savingTimeout = setTimeout(() => { this.isSaving = false; }, 20000);
    },
    stopSaving() {
      this.isSaving = false;
      clearTimeout(this._savingTimeout);
    },
    async templateClick() {
      trackEvent("template", "click", this.diagramType);
      if (this.templateUrl) {
        await openUrl(this.templateUrl);
      }
    },
    async helpClick() {
      trackEvent("help", "click", this.diagramType);
      await openUrl(this.helpUrl);
    },
  },
  async mounted() {
    // Load user's preferred diagram type from localStorage for new diagrams
    const isNewDiagram = this.$store.state.diagram.isNew;
    if (isNewDiagram) {
      const savedDiagramType = localStorage.getItem('zenuml-preferred-diagram-type');
      if (savedDiagramType && (savedDiagramType === DiagramType.Sequence || savedDiagramType === DiagramType.Mermaid)) {
        this.updateDiagramType(savedDiagramType);
      }
    }

    // Store original code for change detection on exit
    this.originalCode = this.currentCode;

    // Pre-resolve cloudId so the synchronous onClose path has it.
    await primeCloudId();

    // Scope: distinguishes "draft for new diagram of this type" from
    // "draft for editing this specific custom-content id".
    this._draftScope = this.$store.state.diagram.id
      ? `edit:${this.$store.state.diagram.id}`
      : `new:${this.diagramType}`;
    this._draftSaver = makeDebouncedDraftSaver(this._draftScope, 500);

    // Restore if a newer draft exists than the loaded diagram.
    const draft = await loadDraft(this._draftScope);
    if (draft) {
      const updatedAt = Number(this.$store.state.diagram.updatedAt) || 0;
      if (draft.savedAt > updatedAt && (draft.code !== this.originalCode || draft.title !== this.$store.state.diagram.title)) {
        EventBus.$emit("draft-available", {
          scope: this._draftScope,
          draft,
        });
      } else {
        // Draft is older than the saved diagram — discard it.
        await clearDraft(this._draftScope);
      }
    }

    // Persist on every change (debounced).
    this._unwatchDraft = this.$watch(
      () => ({ code: this.currentCode, title: this.$store.state.diagram.title }),
      (val) => {
        if (val.code !== this.originalCode || val.title !== '') {
          this._draftSaver?.save({ code: val.code, title: val.title || '' });
        }
      },
    );

    // Wire the platform close hook. ashraf.teleb85 reported the iframe is
    // sometimes destroyed before view.onClose finishes, so we keep the body
    // synchronous: flush the pending debounced write directly to localStorage.
    this._closeGuardOff = setupCloseGuard(() => {
      if (this.currentCode === this.originalCode) return;
      const cloudId = getCachedCloudId();
      if (cloudId) {
        saveDraftSync(this._draftScope, cloudId, {
          code: this.currentCode,
          title: this.$store.state.diagram.title || '',
        });
      }
    });

    // Clear draft + release the Publish button on successful publish. (On the
    // common path view.submit tears the iframe down first, but the viewer-
    // launched modal can stay open, so resetting here matters.)
    this._onPublished = () => {
      this.stopSaving();
      clearDraft(this._draftScope);
    };
    EventBus.$on('saved', this._onPublished);

    // Release the Publish button when a save fails — forgeIndex.ts keeps the
    // dialog open for retry, so without this the spinner would never clear.
    this._onSaveError = () => this.stopSaving();
    EventBus.$on('save-error', this._onSaveError);

    // Restore handler: load the draft into the store + clear it. Uses the
    // diagram-type-specific update action (sequence → updateCode2,
    // mermaid → updateMermaidCode, etc.) so the right code field is set.
    this._onRestore = (payload) => {
      if (payload?.scope !== this._draftScope || !payload?.draft) return;
      const draft = payload.draft;
      const action = getStoreUpdateAction(this.diagramType);
      if (action) this.$store.dispatch(action, draft.code);
      if (draft.title) this.$store.dispatch("updateTitle", draft.title);
      this.originalCode = ''; // force the restored code to be considered dirty
      clearDraft(this._draftScope);
    };
    EventBus.$on('draft-restore', this._onRestore);
  },
  beforeUnmount() {
    this._closeGuardOff?.();
    this._draftSaver?.flush();
    this._unwatchDraft?.();
    clearTimeout(this._savingTimeout);
    if (this._onPublished) EventBus.$off('saved', this._onPublished);
    if (this._onSaveError) EventBus.$off('save-error', this._onSaveError);
    if (this._onRestore) EventBus.$off('draft-restore', this._onRestore);
  },
};
</script>
